### ISSUE TITLE
Error when processing the bond file of a Fe/C/H/O system

### ISSUE THREAD

**Issue by ekritikos** [tongzhugroup/reacnetgenerator#1395]
Hello,

 I am trying to run reacnetgenerator using the command "reacnetgenerator --type bond -i bonds.reaxc -a Fe C H O -n 4" on the bond file of a Fe/C/H/O system. But I get the following error:

2021-12-07 13:10:31,604 - ReacNetGen 1.4.165 - INFO: Version: 1.4.165  Creation date: 2018-03-11
Read bond information and Detect molecules: 0timestep [00:06, ?timestep/s]
2021-12-07 13:10:37,887 - ReacNetGen 1.4.165 - ERROR: run_mp failed
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "reacnetgenerator/_detect.py", line 193, in reacnetgenerator._detect._DetectLAMMPSbond._readstepfunc
  File "reacnetgenerator/_detect.py", line 144, in reacnetgenerator._detect._Detect._connectmolecule
  File "reacnetgenerator/dps.pyx", line 37, in reacnetgenerator.dps.dps
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reacnetgenerator/utils.py", line 440, in reacnetgenerator.utils.run_mp
  File "/home/ekritikos/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not iterable
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "reacnetgenerator/_detect.py", line 193, in reacnetgenerator._detect._DetectLAMMPSbond._readstepfunc
  File "reacnetgenerator/_detect.py", line 144, in reacnetgenerator._detect._Detect._connectmolecule
  File "reacnetgenerator/dps.pyx", line 37, in reacnetgenerator.dps.dps
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ekritikos/anaconda3/bin/reacnetgenerator", line 11, in <module>
    sys.exit(_commandline())
  File "reacnetgenerator/commandline.py", line 59, in reacnetgenerator.commandline._commandline
  File "reacnetgenerator/reacnetgen.py", line 188, in reacnetgenerator.reacnetgen.ReacNetGenerator.runanddraw
  File "reacnetgenerator/reacnetgen.py", line 264, in reacnetgenerator.reacnetgen.ReacNetGenerator._process
  File "reacnetgenerator/_detect.py", line 108, in reacnetgenerator._detect._Detect.detect
  File "reacnetgenerator/_detect.py", line 117, in reacnetgenerator._detect._Detect._readinputfile
  File "reacnetgenerator/_detect.py", line 120, in reacnetgenerator._detect._Detect._readinputfile
  File "reacnetgenerator/utils.py", line 446, in run_mp
  File "reacnetgenerator/utils.py", line 440, in reacnetgenerator.utils.run_mp
  File "/home/ekritikos/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ekritikos/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not iterable

Did you ever come across such a problem? I would appreciate some feedback. Thank you in advance.

**Comment by njzjz** [comment]
There is an error when parsing your input file. If possible, could you please provide a part of your file that will cause the error?

**Comment by ekritikos** [comment]
Thank you for your reply. Please find the bond.reaxc file on the following link: https://we.tl/t-YUgVvph1gZ

**Comment by njzjz** [comment]
@ekritikos Hi, the error happened in Timestep 2857000 (the last step you provided), where there are only 2150 lines (i.e. 2150 atoms). When I deleted that step, it works fine.

**Comment by ekritikos** [comment]
Thank you very much for your help @njzjz, that seems to resolve the reading issue. However, I still have an issue with the output files. Specifically, in the "bonds.reaxc.species" file there is no iron species, and the files "bonds.reaxc.reaction" & "bonds.reaxc.reactionabcd" are empty. The evolution of the system is the following:
# Timestep     No_Moles     No_Specs     Fe2741C84H108O125      C12H26  H2O     H2      O2      
2601000        156          5    1       3       15      22      115    
# Timestep     No_Moles     No_Specs     Fe2741C96H116O121      C12H26  H2      H2O     O2      
2856000        164          5    1       2       27      19      115    
Any feedback on that issue?

**Comment by njzjz** [comment]
This species is not stable so it is filtered. One can add `--nohmm` to the command line to turn off the filter. However, the software failed to handle such large species... If you are running a catalytic reaction, you may consider remove Fe in the trajectory and only see what happens to C/H/O.

**Comment by ekritikos** [comment]
@njzjz Thank you very much for your feedback.
