### ISSUE TITLE
Error of Memory

### ISSUE THREAD

**Issue by yunjian-hash** [tongzhugroup/reacnetgenerator#1630]
Dear developer,

when I use the commend "reacnetgenerator -n 64 -i dump.15.lammpstrj -a H O Si Ca --dump -s Si --nohmm", there is an error:

MemoryError
Traceback (most recent call last):
  File "/public1/home/scb1707/miniconda3/bin/reacnetgenerator", line 8, in <module>
    sys.exit(_commandline())
  File "reacnetgenerator/commandline.py", line 62, in reacnetgenerator.commandline._commandline
  File "reacnetgenerator/reacnetgen.py", line 198, in reacnetgenerator.reacnetgen.ReacNetGenerator.runanddraw
  File "reacnetgenerator/reacnetgen.py", line 289, in reacnetgenerator.reacnetgen.ReacNetGenerator._process
  File "reacnetgenerator/_reachtml.py", line 44, in reacnetgenerator._reachtml._HTMLResult.report
  File "reacnetgenerator/_reachtml.py", line 137, in reacnetgenerator._reachtml._HTMLResult._readdata
  File "reacnetgenerator/_reachtml.py", line 175, in reacnetgenerator._reachtml._HTMLResult._generatesvgs
  File "reacnetgenerator/utils.py", line 446, in run_mp
  File "reacnetgenerator/utils.py", line 440, in reacnetgenerator.utils.run_mp
  File "/public1/home/scb1707/miniconda3/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/public1/home/scb1707/miniconda3/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/public1/home/scb1707/miniconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/public1/home/scb1707/miniconda3/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/public1/home/scb1707/miniconda3/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/public1/home/scb1707/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

How could I fix it? The attached is the output by reacnetgenerator. Thanks!

[slurm-1389281.txt](https://github.com/tongzhugroup/reacnetgenerator/files/9129468/slurm-1389281.txt)

**Comment by njzjz** [comment]
This error is "out of memory".

**Comment by njzjz** [comment]
This method is removed in #1641, and the related feature is refactored, so this will not happen anymore.
